### ISSUE TITLE
[SOLVED] CSS not loading until forced purge

### ISSUE THREAD

**Issue by ghost** [enterprisemediawiki/MasonryMainPage#13]
Masonry-blocks will not render until I purge the page's cache (?action=purge). I've checked on multiple browsers, and in all cases there are missing scripts until the page is purged on the user's end.

**Comment by jamesmontalvo3** [comment]
Is that not typical if you have caching enabled?

**Comment by ghost** [comment]
Right! I did figure out that using `$wgEnableParserCache=false; ` was helpful, but I had to do a bit of searching. Since I'm kinda new to MW, I'm under the impression that normally a page is cached until it's edited, and then the cache for the page is cleared. It then made sense that this automatic process would work with MMP. I think the parserCache setting would make a nice addition to the instructions :)

**Comment by jamesmontalvo3** [comment]
MediaWiki does a lot of different types of caching. Take a look at:

* [Manual:Caching](https://www.mediawiki.org/wiki/Manual:Caching)
* [Manual:Performance tuning](https://www.mediawiki.org/wiki/Manual:Performance_tuning)
