### ISSUE TITLE
Masonry intermittently does not arrange blocks upon page load

### ISSUE THREAD

**Issue by darenwelsh** [enterprisemediawiki/MasonryMainPage#2]
When loading a MediaWiki page that uses MasonryMainPage, sometimes masonry will arrange the blocks and sometimes it will not. It is not clear if there is a conflict with div IDs, CSS, or something within the masonry or imagesLoaded scripts.

**Comment by darenwelsh** [comment]
I have not seen this issue in a long time. Since we just merged a new way of loading (#5) and that tested successfully, I think this is okay to close.

**Comment by JosefAssad** [comment]
I'm seeing an issue, it's possible this is the same one.

With MW 1.27, I'm getting the blocks arranged in a vertical line, they aren't making use of the horizontal space. Is that the same thing you were seeing?

**Comment by darenwelsh** [comment]
Sorry I didn't notice your comment until just now. I think you're describing the same behavior. Is it consistent or intermittent? Any console or debug messages?

**Comment by JosefAssad** [comment]
It's 100% consistent, which is convenient :)

It looks like this:

![mmp-stacking](https://cloud.githubusercontent.com/assets/1040956/19597873/953f344e-9797-11e6-9279-afeab55b0b89.png)

The console does indeed throw an exception:

TypeError: EventEmitter is not a constructor
http://REDACTED_HOST/load.php?debug=false&lang=en&modules=ext.jquery.blockUI%7Cext.jquery.jqplot.core%2Cpie%7Cext.jquery.migration.browser%7Cext.masonrymainpage.base%7Cext.srf.jqplot.chart%2Cpie%2Cthemes%7Cjquery.accessKeyLabel%2Casync%2CbyteLength%2Cclient%2CtabIndex%2Cthrottle-debounce%7Cmediawiki.RegExp%2CTitle%2CUri%2Cnotify%2Ctemplate%2Cutil%7Cmediawiki.page.startup%7Cmediawiki.template.regexp%7Cskins.vector.js&skin=vector&version=0d2cf39c442e
Line 227

Screenshot from the console:

![exception](https://cloud.githubusercontent.com/assets/1040956/19597857/7bbb591c-9797-11e6-9e8a-89bad2929348.png)

I can't see much in the apache logs or mw debug log that might appear relevant. Happy as ever to provide any extras info. :)

**Comment by gadgetmg** [comment]
I'm seeing this exact behavior as well.

**Comment by bryandamon** [comment]
I'm now seeing this behavior as well.  The blocks always are arranged in a vertical line, but intermittently the blocks lose their formatting.  I recently upgraded my wiki from 1.26 to 1.28.2.

## Vertical Blocks
------------
![main-partial](https://cloud.githubusercontent.com/assets/10904060/25792118/7e6e07ee-3379-11e7-8ae8-6408c7634284.PNG)
------------
## Vertical Blocks and loss of formatting
------------
 ![main-none](https://cloud.githubusercontent.com/assets/10904060/25792119/7e6e6eb4-3379-11e7-80f2-d9e71c9960e6.PNG)
------------

**Comment by jamesmontalvo3** [comment]
@bryandamon: Have you upgraded MasonryMainPage? What version are you on? If you're using git you can do `cd /path/to/mediawiki/extensions/MasonryMainPage` and then `git rev-parse HEAD` and report the An upgrade was required when jumping from MW1.25 to 1.27. I have not tested on 1.28 specifically.

**Comment by JosefMikkelsen** [comment]
I still experience this issue. MW 1.27.1 here, and MasonryMainPage is at commit 9837244ccf70f3823e8f5366045e1637e65bd993. I've checked it in several browsers, same issue. The js console complains about:

```
ReferenceError: imagesLoaded is not defined
http://wiki/load.php?debug=false&lang=en&modules=ext.jquery.blockUI%7Cext.jquery.jqplot.core%2Cpie%7Cext.jquery.migration.browser%7Cext.masonrymainpage.base%7Cext.srf.jqplot.chart%2Cpie%2Cthemes%7Cjquery.accessKeyLabel%2Casync%2CbyteLength%2Cclient%2CtabIndex%2Cthrottle-debounce%7Cmediawiki.RegExp%2CTitle%2CUri%2Cnotify%2Ctemplate%2Cutil%7Cmediawiki.page.startup%7Cmediawiki.template.regexp%7Cskins.vector.js&skin=vector&version=2dcda0e27f37
Line 221
```

I noticed the (new) notice in the MasonryMainPage README to install the [ImagesLoaded](https://github.com/enterprisemediawiki/ImagesLoaded) library; I dropped that in my extensions folder. Wasn't entirely sure how to load it so I dropped a `require_once "$IP/extensions/ImagesLoaded/ImagesLoaded.class.php"; in my `LocalSettings.php` like any reckless idiot would do (even though I'm pretty sure that isn't how it's loaded) and the blocks are still stacking vertically; no joy. Is that ImagesLoaded library required? and is it something we're meant to use composer to install?

**Comment by jamesmontalvo3** [comment]
Not composer, but need to use the new MediaWiki method of loading extensions, e.g.

```
wfLoadExtensions( 'ImagesLoaded' );
```

Sorry this isn't listed in the docs. I've been trying to get several things updated to current MediaWiki versions and I just created an issue against Extension:ImagesLoaded to [remember to circle back and add docs](https://github.com/enterprisemediawiki/ImagesLoaded/issues/1). Pull requests welcome. :)

Note that MasonryMainPage can be loaded in the above method, as well, but does not require it.

**Comment by jamesmontalvo3** [comment]
For more info on extension registration: https://www.mediawiki.org/wiki/Manual:Extension_registration

**Comment by JosefMikkelsen** [comment]
Aye, that fixed it! ty James! Minor defail in case anyone else is tracking this issue, it's `wfLoadExtension( 'ImagesLoaded' );` not `wfLoadExtensions( 'ImagesLoaded' );` :)

**Comment by bryandamon** [comment]
Hi @jamesmontalvo3, I just upgraded to commit `9837244` and also installed ImagesLoaded (which I did not have on MW 1.26).  The problem persists, always blocks in columns, occasionally I get formatting.  For whatever reason, after running `update.php` the formatting comes back until a refresh.

**Comment by bryandamon** [comment]
Quick update.  I also loaded MasonryMainPage using `wfLoadExtension( 'MasonryMainPage' );` vs. the old way (which I don't think matters) but now after running `update.php` (or any edit to **LocalSettings.php**) I get everything right, both formatting and proper stacking of the blocks until a refresh, then after every subsequent refresh the issue persists.

Note, it's late, it very well could have done the same (formatting and stacking) after the update to commit `9837244` and/or the addition of ImagesLoaded.

**Comment by jamesmontalvo3** [comment]
@bryandamon what are you seeing if you open your browser's javascript console? How to open it [differs based on your browser and operating system](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers). After you open it you may need to refresh your MasonryMainPage page to see if it gives any errors. If there are many errors, feel free to just screenshot them.

**Comment by bryandamon** [comment]
@jamesmontalvo3, I do have the following error:
`load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector:4 [c66163393a6b52e6c07a4b3e] /load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector BadMethodCallException from line 845 of /apps/mediawiki/htdocs/includes/session/SessionManager.php: Sessions are disabled for this entry point`

I believe it has to do with an [incompatibility](https://www.mediawiki.org/wiki/Topic:Tmrlqagno27nsun0) between MW 1.28.2 and the version of SMW I have now, but maybe it's also creating a problem with MasonryMainPage as well? 

### Update
Uninstalling SMW removed the above warning, but the MasonryMainPage issue remains.
